# Generated by Django 5.2.1 on 2025-06-02 17:19

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('requisites', models.TextField(help_text='Банковские реквизиты компании', verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введите название жанра (например, 'Фантастика', 'Драма')", max_length=50, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Уникальный номер кинозала', unique=True, verbose_name='Номер зала')),
                ('capacity', models.PositiveIntegerField(help_text='Количество мест в зале', verbose_name='Вместимость')),
                ('hall_type', models.CharField(choices=[('2D', 'Стандартный 2D'), ('3D', '3D-зал'), ('IMAX', 'IMAX'), ('VIP', 'VIP-зал')], default='2D', max_length=20, verbose_name='Тип зала')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о зале', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('summary', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Зарплата ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата размещения')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('cashier', 'Кассир'), ('manager', 'Менеджер'), ('admin', 'Администратор'), ('cleaner', 'Уборщик')], max_length=20, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('birth_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='Дата рождения не может быть ранее 1900 года')], verbose_name='Дата рождения')),
                ('photo', models.ImageField(help_text='Рекомендуемый размер: 300x300 px', upload_to='employees/', verbose_name='Фотография')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Дата приёма на работу')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('duration', models.PositiveIntegerField(help_text='Продолжительность в минутах', verbose_name='Длительность (мин)')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('age_limit', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=3, verbose_name='Возрастное ограничение')),
                ('country', models.CharField(max_length=100, verbose_name='Страна производства')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('poster', models.ImageField(help_text='Рекомендуемый размер: 600x900 px', upload_to='posters/', verbose_name='Постер')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Укажите сумму в долларах', max_digits=12, verbose_name='Бюджет ($)')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Рейтинг')),
                ('genres', models.ManyToManyField(related_name='movies', to='cinema.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(editable=False, verbose_name='Время окончания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена билета')),
                ('available_seats', models.PositiveIntegerField(default=0, verbose_name='Свободные места')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.hall', verbose_name='Зал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='Номер места')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итоговая цена')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.session', verbose_name='Сеанс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date'], name='cinema_movi_release_31f56f_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='cinema_movi_rating_1ca34f_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['hall', 'start_time'], name='cinema_sess_hall_id_13b6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['available_seats'], name='cinema_sess_availab_ac8e95_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('hall', 'start_time'), name='unique_session_time'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('session', 'seat_number'), name='unique_seat_per_session'),
        ),
    ]
