# Generated by Django 5.2.1 on 2025-05-26 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введите название жанра (например, 'Фантастика', 'Драма')", max_length=50, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Уникальный номер кинозала', unique=True, verbose_name='Номер зала')),
                ('capacity', models.PositiveIntegerField(help_text='Количество мест в зале', verbose_name='Вместимость')),
                ('hall_type', models.CharField(choices=[('2D', 'Стандартный 2D'), ('3D', '3D-зал'), ('IMAX', 'IMAX'), ('VIP', 'VIP-зал')], default='2D', max_length=20, verbose_name='Тип зала')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о зале', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('duration', models.PositiveIntegerField(help_text='Продолжительность в минутах', verbose_name='Длительность (мин)')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('age_limit', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=3, verbose_name='Возрастное ограничение')),
                ('country', models.CharField(max_length=100, verbose_name='Страна производства')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('poster', models.ImageField(help_text='Рекомендуемый размер: 600x900 px', upload_to='posters/', verbose_name='Постер')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Укажите сумму в долларах', max_digits=12, verbose_name='Бюджет ($)')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Рейтинг')),
                ('genres', models.ManyToManyField(related_name='movies', to='cinema.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-release_date', 'title'],
                'indexes': [models.Index(fields=['-release_date'], name='cinema_movi_release_31f56f_idx'), models.Index(fields=['rating'], name='cinema_movi_rating_1ca34f_idx')],
            },
        ),
    ]
