# Generated by Django 5.2.1 on 2025-06-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
