# Generated by Django 5.2.1 on 2025-06-02 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_about_created_at_remove_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
