# Generated by Django 5.2.1 on 2025-06-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_about_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Словарь терминов и FAQ'},
        ),
        migrations.AddField(
            model_name='faq',
            name='entry_type',
            field=models.CharField(choices=[('question', 'Частый вопрос'), ('term', 'Термин глоссария')], default='question', max_length=10, verbose_name='Тип записи'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ/Определение'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Вопрос/Термин'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['entry_type'], name='cinema_faq_entry_t_7d4d53_idx'),
        ),
    ]
