services:
  mongodb:
    image: mongo:latest
    container_name: cinema-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cinema-app
    restart: always
    command: mongod --auth

  app:
    build: .
    container_name: cinema-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://cinema_user:cinema_password@mongodb:27017/cinema-app
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cinema-client
    ports:
      - "3000:3000"
    depends_on:
      - app
    restart: always

volumes:
  mongodb_data: