# Generated by Django 5.2.1 on 2025-06-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_client_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
