# Generated by Django 5.2.1 on 2025-06-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superuser', 'Владелец'), ('registered', 'Зарегистрированный пользователь'), ('guest', 'Гостевой пользователь')], default='guest', max_length=20),
        ),
    ]
