# Generated by Django 5.2.1 on 2025-06-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Итоговая цена'),
        ),
    ]
