# Generated by Django 5.2.1 on 2025-06-03 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_ticket_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итоговая цена'),
        ),
    ]
