# Generated by Django 5.2.6 on 2025-09-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_mainpagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpagemodel',
            options={'verbose_name': 'Главная страница'},
        ),
    ]
