# Generated by Django 5.2.6 on 2025-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_mainpagemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='adb/', verbose_name='Баннер')),
                ('src', models.TextField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
            },
        ),
        migrations.RenameModel(
            old_name='MainPageModel',
            new_name='LogoModel',
        ),
        migrations.AlterModelOptions(
            name='logomodel',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
    ]
