# Generated by Django 5.2.6 on 2025-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_advmodel_rename_mainpagemodel_logomodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='sponsors/', verbose_name='Баннер')),
                ('src', models.TextField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
    ]
