# Generated by Django 5.2.6 on 2025-09-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_sponsormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('text', models.TextField(verbose_name='Описание события')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cinema.about')),
            ],
            options={
                'verbose_name': 'Событие истории',
                'verbose_name_plural': 'События истории',
                'ordering': ['year'],
            },
        ),
    ]
