# Generated by Django 5.2.6 on 2025-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_about_video_historyevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyevent',
            options={'ordering': ['-year'], 'verbose_name': 'Событие истории', 'verbose_name_plural': 'События истории'},
        ),
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='about',
            name='bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='about',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='about',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='about',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН'),
        ),
    ]
