# Generated by Django 5.2.6 on 2025-09-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_alter_historyevent_options_about_address_about_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сертификата')),
                ('description', models.TextField(verbose_name='Описание сертификата')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='Организация, выдавшая сертификат')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='cinema.about')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
