# Generated by Django 5.2.6 on 2025-09-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_ticket_is_paid_ticket_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('cash', 'Наличные')], max_length=10, null=True, verbose_name='Способ оплаты'),
        ),
    ]
