# Generated by Django 5.2.7 on 2025-10-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_ticket_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormodel',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
