# Generated by Django 5.2.7 on 2025-11-19 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0017_sponsormodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.BooleanField(default=True, verbose_name='Зацикливание (loop)')),
                ('navs', models.BooleanField(default=True, verbose_name='Показывать стрелки (navs)')),
                ('pags', models.BooleanField(default=True, verbose_name='Показывать пагинацию (pags)')),
                ('auto', models.BooleanField(default=True, verbose_name='Автоматическая прокрутка (auto)')),
                ('stop_mouse_hover', models.BooleanField(default=True, verbose_name='Останавливать при наведении (stopMouseHover)')),
                ('delay', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Интервал между слайдами (сек)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Настройки слайдера',
                'verbose_name_plural': 'Настройки слайдера',
            },
        ),
    ]
