# Generated by Django 5.2.7 on 2025-11-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_slidersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, help_text='Описание выполняемых работ сотрудником', null=True, verbose_name='Описание работы'),
        ),
    ]
